import type { DashboardIngestion } from "../ingestion/dashboard-ingestion";
import type { CalendarEvent, NewsItem } from "../data/types";
import type { Context, Evidence, Event, Observation, ProviderHealth } from "../domain/types";
import type { EconomicEventResult } from "../domain/event-result";
import { buildDashboardContexts } from "../domain/context";
import { normalizeBiquoteEconomicCalendar } from "./biquote-economic-calendar";
import { calendarToCanonicalRecords, cryptoMarketToObservations, fomcToCanonicalRecords, macroToCanonicalRecords, newsToEvidence, providerHealthForResult, P365_SOURCES } from "../domain/normalize";
export type NormalizedDashboardData = { macroNews: NewsItem[]; cryptoNews: NewsItem[]; calendarEvents: CalendarEvent[]; calendarProviderMessage?: string; unavailableSources: string[]; observations: Observation[]; macroObservations: Observation[]; events: Event[]; economicEventResults: EconomicEventResult[]; contexts: Context[]; evidence: Evidence[]; providerHealth: ProviderHealth[] };
function normalizeNewsUrl(url: string): string { return url.trim().replace(/#.*$/, "").replace(/\/+$/, "").toLowerCase(); }
function dedupeNewsBySource(items: NewsItem[], sourceId: string): NewsItem[] { const seen = new Set<string>(); return items.filter((item) => { const key = `${sourceId}:${normalizeNewsUrl(item.url)}`; if (!normalizeNewsUrl(item.url) || seen.has(key)) return false; seen.add(key); return true; }); }
function dedupeByTitle(items: NewsItem[]): NewsItem[] { const seen = new Set<string>(); return items.filter((item) => { const key = item.title.trim().toLowerCase(); if (!key || seen.has(key)) return false; seen.add(key); return true; }); }
function sortByRecency(items: NewsItem[]): NewsItem[] { return [...items].sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()); }
function jakartaDate(dateISO: string): string { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Jakarta", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date(dateISO)); const value = (type: Intl.DateTimeFormatPartTypes) => parts.find((part) => part.type === type)?.value; return `${value("year")}-${value("month")}-${value("day")}`; }
function isFomcCalendarEvent(item: CalendarEvent): boolean { return /\bfomc\b|federal open market committee/i.test(item.event); }
function dedupeCalendarEvents(calendarEvents: CalendarEvent[], fomcDates: string[]): CalendarEvent[] { const officialFomcDates = new Set(fomcDates.map(jakartaDate)); return calendarEvents.filter((item) => !isFomcCalendarEvent(item) || !officialFomcDates.has(jakartaDate(item.dateISO))); }
export function normalizeDashboardData(input: DashboardIngestion): NormalizedDashboardData {
  const macroNews = dedupeNewsBySource(input.macroNews.data, P365_SOURCES.alphaVantage.id); const avCrypto = dedupeNewsBySource(input.alphaVantageCryptoNews.data, P365_SOURCES.alphaVantage.id); const coinDesk = dedupeNewsBySource(input.coinDeskNews.data, P365_SOURCES.coinDesk.id); const cryptoNews = sortByRecency(dedupeByTitle([...coinDesk, ...avCrypto])).slice(0, 6);
  const calendarEvents = dedupeCalendarEvents(input.calendar.data, input.fomc.data.map((item) => item.scheduledAt)); const unavailableSources: string[] = [];
  if (input.macroNews.status !== "SUCCESS") unavailableSources.push(`berita makro (Alpha Vantage: ${input.macroNews.status})`); if (cryptoNews.length === 0 || (input.coinDeskNews.status !== "SUCCESS" && input.alphaVantageCryptoNews.status !== "SUCCESS")) unavailableSources.push(`berita crypto (CoinDesk: ${input.coinDeskNews.status}; Alpha Vantage: ${input.alphaVantageCryptoNews.status})`); if (input.calendar.status !== "SUCCESS") unavailableSources.push(`kalender ekonomi (Forex Factory: ${input.calendar.status})`); if (input.biquoteCalendar.status !== "SUCCESS") unavailableSources.push(`economic-event result (Biquote: ${input.biquoteCalendar.status})`); if (input.cryptoMarket.status !== "SUCCESS") unavailableSources.push(`market crypto (CoinGecko: ${input.cryptoMarket.status})`); if (input.goldSpot.status !== "SUCCESS" && input.russell2000.status !== "SUCCESS" && input.dxy.status !== "SUCCESS") unavailableSources.push(`emas, Russell 2000 & DXY (Yahoo Finance: ${input.goldSpot.status}/${input.russell2000.status}/${input.dxy.status})`); if (input.fred.status !== "SUCCESS") unavailableSources.push(`observasi makro (FRED: ${input.fred.status})`); if (input.fomc.status !== "SUCCESS") unavailableSources.push(`event FOMC (Federal Reserve: ${input.fomc.status})`);
  const newsEvidence = [...newsToEvidence(macroNews, P365_SOURCES.alphaVantage.id), ...newsToEvidence(avCrypto, P365_SOURCES.alphaVantage.id), ...newsToEvidence(coinDesk, P365_SOURCES.coinDesk.id)]; const calendarRecords = calendarToCanonicalRecords(calendarEvents, P365_SOURCES.forexFactory.id); const fomcRecords = fomcToCanonicalRecords(input.fomc.data, P365_SOURCES.federalReserve.id); const biquoteRecords = normalizeBiquoteEconomicCalendar(input.biquoteCalendar.data, input.biquoteCalendar.retrievedAt); const events = [...calendarRecords.events, ...fomcRecords.events, ...biquoteRecords.map((item) => item.event)]; const economicEventResults = biquoteRecords.map((item) => item.result); const marketFacts = cryptoMarketToObservations(input.cryptoMarket.data, P365_SOURCES.coinGeckoMarket.id); const extraMarketFacts = cryptoMarketToObservations([...input.goldSpot.data, ...input.russell2000.data, ...input.dxy.data], P365_SOURCES.yahooFinance.id); const macroFacts = macroToCanonicalRecords(input.fred.data, P365_SOURCES.fred.id); const fredHealth = providerHealthForResult(P365_SOURCES.fred.id, input.fred); if (input.fred.status === "SUCCESS" && macroFacts.observations.length > 0 && macroFacts.observations.every((item) => item.quality === "STALE")) fredHealth.status = "STALE";
  const observations = [...marketFacts.observations, ...extraMarketFacts.observations, ...macroFacts.observations]; const evidence = [...newsEvidence, ...calendarRecords.evidence, ...fomcRecords.evidence, ...biquoteRecords.map((item) => item.evidence), ...marketFacts.evidence, ...extraMarketFacts.evidence, ...macroFacts.evidence]; const contexts = buildDashboardContexts({ observations, events }); const macroObservations = macroFacts.observations.filter((item) => item.domain === "MACRO"); const yahooMarketSucceeded = input.goldSpot.status === "SUCCESS" || input.russell2000.status === "SUCCESS" || input.dxy.status === "SUCCESS"; const yahooMarketHealth = providerHealthForResult(P365_SOURCES.yahooFinance.id, yahooMarketSucceeded ? { ...input.goldSpot, status: "SUCCESS" as const, data: [...input.goldSpot.data, ...input.russell2000.data, ...input.dxy.data] } : input.goldSpot); const providerHealth = [providerHealthForResult(P365_SOURCES.alphaVantage.id, input.macroNews), providerHealthForResult(P365_SOURCES.coinDesk.id, input.coinDeskNews), providerHealthForResult(P365_SOURCES.forexFactory.id, input.calendar), providerHealthForResult(P365_SOURCES.biquote.id, input.biquoteCalendar), providerHealthForResult(P365_SOURCES.coinGeckoMarket.id, input.cryptoMarket), yahooMarketHealth, fredHealth, providerHealthForResult(P365_SOURCES.federalReserve.id, input.fomc)];
  return { macroNews: sortByRecency(macroNews), cryptoNews, calendarEvents, calendarProviderMessage: input.calendar.message, unavailableSources, observations, macroObservations, events, economicEventResults, contexts, evidence, providerHealth };
}
