"use client";

import { useState } from "react";
import { relativeTimeID } from "@/lib/data/format";
import type { DashboardData } from "@/lib/data/dashboard-data";
import type { CalendarEvent, NewsItem } from "@/lib/data/types";
import type { DataQuality, ProviderHealth } from "@/lib/domain/types";
import { logout } from "./actions";

type Menu = "overview" | "macro" | "crypto" | "intelligence" | "evidence";
const menuItems: { id: Menu; label: string }[] = [
  { id: "overview", label: "Overview" }, { id: "macro", label: "Macro" }, { id: "crypto", label: "Crypto" },
  { id: "intelligence", label: "Intelligence" }, { id: "evidence", label: "Evidence" },
];

function StatusBadge({ value }: { value: "PENDING" | "FRESH" | "PARTIAL" | "UNAVAILABLE" }) {
  const labels = { PENDING: "BELUM ADA", FRESH: "TERBARU", PARTIAL: "SEBAGIAN", UNAVAILABLE: "TIDAK TERSEDIA" };
  return <span className={`status-badge ${value.toLowerCase()}`}>{labels[value]}</span>;
}
function EmptyPanelNote({ label }: { label: string }) { return <p className="muted">Data {label} belum tersedia saat ini. Coba muat ulang beberapa saat lagi.</p>; }
function NewsCard({ item }: { item: NewsItem }) { return <article className="evidence-item"><div className="card-meta"><span>{item.category}</span><span>{item.source} · {relativeTimeID(item.publishedAt)}</span></div><h3>{item.title}</h3><p>{item.summary}</p><a className="text-link" href={item.url} target="_blank" rel="noreferrer">Baca sumber ↗</a></article>; }
function CalendarRow({ item }: { item: CalendarEvent }) { return <article className="calendar-row"><time dateTime={item.dateISO} aria-label={`${item.event}, ${item.status}, ${item.time} WIB`}>{item.time}<small>WIB</small></time><div><h3>{item.event}</h3><p>{item.country} · {item.status}</p></div><span className={`impact ${item.impact.toLowerCase()}`}>{item.impact}</span></article>; }
function observationStatus(qualities: DataQuality[]): "PENDING" | "FRESH" | "PARTIAL" { return qualities.length === 0 ? "PENDING" : qualities.every((item) => item === "FRESH") ? "FRESH" : "PARTIAL"; }
function sourceStatus(health: ProviderHealth[]): "PENDING" | "FRESH" | "PARTIAL" | "UNAVAILABLE" { if (!health.length) return "PENDING"; if (health.some((item) => item.status === "ERROR" || item.status === "UNAVAILABLE")) return "UNAVAILABLE"; if (health.some((item) => item.status === "STALE")) return "PARTIAL"; return health.some((item) => item.status === "EMPTY") ? "PENDING" : "FRESH"; }

export function DashboardView({ data, sessionEmail }: { data: DashboardData; sessionEmail: string }) {
  const [activeMenu, setActiveMenu] = useState<Menu>("overview");
  const { macroNews, cryptoNews, calendarEvents, unavailableSources, observations, evidence, providerHealth } = data;
  const marketStatus = observationStatus(observations.map((item) => item.quality));
  const providerStatus = sourceStatus(providerHealth);
  const highImpactEvents = calendarEvents.filter((item) => item.impact === "HIGH").length;
  const showNews = (items: NewsItem[], label: string) => <section className="panel news-panel"><div className="panel-label"><span>{label}</span><span>{items.length} ITEM</span></div><h2>Evidence berita terbaru</h2><div className="news-list">{items.length ? items.map((item) => <NewsCard item={item} key={item.id} />) : <EmptyPanelNote label={label.toLowerCase()} />}</div></section>;

  return <main className="dashboard-shell">
    <header className="topbar"><div><div className="brand-lockup"><span className="brand-mark" aria-hidden="true">P</span><p className="eyebrow">P365 // MARKET INTELLIGENCE</p></div><h1>Market Intelligence<span>.</span></h1></div><div className="topbar-actions"><p><span className={`live-dot ${providerStatus === "UNAVAILABLE" ? "warning" : ""}`} /> {providerStatus === "FRESH" ? "DATA SEHAT" : "PERLU PERHATIAN"}</p><form action={logout}><button className="logout" type="submit">Keluar</button></form></div></header>
    <nav className="filters" aria-label="Bagian dashboard" role="tablist">{menuItems.map((item) => <button key={item.id} type="button" role="tab" aria-selected={activeMenu === item.id} className={activeMenu === item.id ? "active" : ""} onClick={() => setActiveMenu(item.id)}>{item.label}</button>)}<span>WIB / ASIA-JAKARTA</span></nav>

    <div className="dashboard-content" role="tabpanel">
      {activeMenu === "overview" && <><section className="market-state panel" aria-labelledby="state-title"><div className="panel-label"><span>01 / STATUS PASAR GLOBAL</span><StatusBadge value="PENDING" /></div><div className="state-grid"><div><h2 id="state-title">Belum ada kesimpulan status pasar.</h2><p>{observations.length ? "Observasi pasar tersedia, tetapi P365 belum memiliki aturan domain spesifik untuk menggabungkannya menjadi satu status pasar." : "Tidak ada observasi pasar yang dapat diverifikasi pada request ini, sehingga P365 tidak menampilkan status pasar."}</p></div><div className="state-meta"><div><span>CONFIDENCE</span><strong>BELUM ADA</strong></div><div><span>OBSERVASI</span><strong>{observations.length} · {marketStatus}</strong></div><div><span>EVIDENCE KANONIK</span><strong>{evidence.length} item</strong></div><div><span>EVENT MENDATANG</span><strong>{calendarEvents.length}</strong></div></div></div></section><section className="overview-grid"><section className="panel market-watch"><div className="panel-label"><span>CAKUPAN DOMAIN</span><span>RINGKASAN</span></div><h2>Cakupan data</h2>{[["Evidence berita makro", macroNews.length, macroNews.length ? "FRESH" : "PENDING"], ["Evidence berita crypto", cryptoNews.length, cryptoNews.length ? "FRESH" : "PENDING"], ["Observasi pasar", observations.length, marketStatus], ["Provider", providerHealth.length, providerStatus]].map(([label, count, status]) => <div className="watch-row" key={String(label)}><span>{label}</span><strong>{count}</strong><StatusBadge value={status as "PENDING" | "FRESH" | "PARTIAL" | "UNAVAILABLE"} /></div>)}</section><section className="panel calendar"><div className="panel-label"><span>EVENT MENDATANG</span><span>{calendarEvents.length} ITEM</span></div><h2>Agenda penting</h2>{calendarEvents.length ? calendarEvents.map((item) => <CalendarRow item={item} key={item.id} />) : <EmptyPanelNote label="kalender ekonomi" />}</section></section></>}
      {activeMenu === "macro" && showNews(macroNews, "BERITA MAKRO")}
      {activeMenu === "crypto" && <div className="menu-grid">{showNews(cryptoNews, "BERITA CRYPTO")}<section className="panel"><div className="panel-label"><span>OBSERVASI PASAR</span><StatusBadge value={marketStatus} /></div><h2>Crypto market watch</h2><div className="monitor-list"><div><strong>Observasi kanonik</strong><span>{observations.length} observasi pasar tersedia.</span></div><div><strong>Kualitas data</strong><span>Status observasi saat ini: {marketStatus}.</span></div></div></section></div>}
      {activeMenu === "intelligence" && <div className="menu-grid"><section className="panel intelligence-panel"><div className="panel-label"><span>MARKET INTELLIGENCE</span><span>SEMANTIC CONTRACT</span></div><h2>Interpretasi belum tersedia.</h2><p className="lead-copy">P365 hanya menampilkan interpretasi bila evidence cukup kuat; headline mentah, event, atau observasi tunggal bukan market intelligence.</p><div className="reasoning-grid">{[["WHAT", "Belum ada interpretasi yang tersusun."], ["WHY", "Ambang batas semantik tingkat lanjut belum didefinisikan."], ["CONFIRMS", "Evidence kanonik tersedia di menu Evidence."], ["CONTRADICTS", "Belum ada klaim intelligence aktif untuk dibantah."], ["INVALIDATES", "Belum ada interpretasi aktif."], ["MONITOR", "Pantau observasi, provider, dan event mendatang."]].map(([title, copy]) => <div key={title}><span>{title}</span><p>{copy}</p></div>)}</div><div className="intelligence-footer"><div><span>CONFIDENCE</span><StatusBadge value="PENDING" /></div><div><span>EVIDENCE KANONIK</span><strong>{evidence.length}</strong></div></div></section><section className="panel"><div className="panel-label"><span>MONITOR</span><span>STATUS OPERASIONAL</span></div><h2>Apa yang perlu dipantau?</h2><div className="monitor-list"><div><strong>Observasi pasar</strong><span>{observations.length} observasi · kualitas {marketStatus}.</span></div><div><strong>Event makro</strong><span>{highImpactEvents} event berdampak tinggi saat ini.</span></div><div><strong>Kesehatan provider</strong><span>{providerStatus === "FRESH" ? "Semua provider sehat." : "Satu atau lebih provider perlu perhatian."}</span></div></div></section></div>}
      {activeMenu === "evidence" && <div className="menu-grid">{showNews(macroNews, "EVIDENCE BERITA MAKRO")} {showNews(cryptoNews, "EVIDENCE BERITA CRYPTO")}<section className="panel data-health"><div className="panel-label"><span>KESEHATAN DATA</span><span>{providerStatus === "FRESH" ? "SEHAT" : "PERLU PERHATIAN"}</span></div><h2>Status sumber data</h2>{unavailableSources.length ? <><p className="health-warning">Sebagian sumber data tidak tersedia. Ini bukan berarti datanya kosong.</p><div className="source-list">{unavailableSources.map((source) => <span key={source}>{source}</span>)}</div></> : <p className="health-ok">Semua sumber data yang dikonfigurasi mengembalikan data untuk request ini.</p>}</section></div>}
    </div>
    <section className="panel profile"><p className="panel-label">SESI</p><p>Masuk sebagai</p><strong>{sessionEmail}</strong></section>
  </main>;
}
